---
- name: Print RouterBOARD Name Sample
  hosts: all
  gather_facts: no
  tasks:
    - name: Log Messages
      raw: "{ :log info \"AWX Entrando\"; :log info (\"Nome da RB: \" . [/system identity get name]); :log info \"AWX Saindo\"; quit; }"

