---
- name: Print RouterBOARD Name Sample
  hosts: all
  gather_facts: no
  tasks:
    - name: Get RouterBOARD Name
      raw: /system identity print
      register: result

    - name: Print RouterBOARD Name
      debug:
        msg: "The RouterBOARD name is {{ result.stdout }}"
