---
- name: Print RouterBOARD Name Sample
  hosts: all
  gather_facts: no
  tasks:
    - name: Get RouterBOARD Name
      raw: ':put ("@@@".[/system identity get name]."@@@"); quit;'
      register: rb_name
      changed_when: false

    - name: Clean Control Characters and Extract RouterBOARD Name
      set_fact:
        cleaned_rb_name: "{{ rb_name.stdout | regex_replace('\r|\n|\u001b\\[[0-9;]*[mB]', '') | regex_replace('.*?@@@(.*?)@@@.*', '\\1') }}"

    - name: Print Message
      debug:
        msg: "Comandos executados no dispositivo: {{ cleaned_rb_name }}"
