---
- name: Print RouterBOARD Name Sample
  hosts: all
  gather_facts: no
  tasks:
    - name: Log Messages
      raw: "{ :log info \"AWX Entrando\"; :log info (\"Nome da RB: \" . [/system identity get name]); :log info \"AWX Saindo\"; quit; }"
      register: result

    - name: Print Message
      debug:
        msg: "Comandos executados no dispositivo: {{ result.stdout_lines[0].split(':')[1].strip() }}"